name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PASSWORD: mypassword123   # ❌ insecure

    steps:
      - uses: actions/checkout@v3

      - name: Print Password
        run: echo $PASSWORD
